package co.caio.cerberus;

import com.google.protobuf.util.JsonFormat;

import java.util.List;
import java.util.Optional;

public class Recipe {
    private Generated.Recipe protoRecipe;

    private Recipe(Generated.Recipe recipe) {
        assert (recipe != null);
        protoRecipe = recipe;
    }

    public static Optional<Recipe> fromJson(String json) {
        try {
            var builder = Generated.Recipe.newBuilder();
            JsonFormat.parser().merge(json, builder);
            return Optional.of(new Recipe(builder.build()));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    private Optional<Integer> optionalUint(int n) {
        if (n < 0) {
            return Optional.empty();
        } else {
            return Optional.of(n);
        }
    }

    private Optional<Integer> getDuration(String name) {
        return optionalUint(protoRecipe.getDurationOrDefault(name, -1));
    }

    private Optional<Integer> getNutrition(String name) {
        return optionalUint(protoRecipe.getNutritionOrDefault(name, -1));
    }

    public Optional<Integer> getPrepTime() {
        return getDuration("prepTime");
    }

    public Optional<Integer> getCookTime() {
        return getDuration("cookTime");
    }

    public Optional<Integer> getTotalTime() {
        return getDuration("totalTime");
    }

    public Optional<Integer> getCalories() {
        return getNutrition("calories");
    }

    public Optional<Integer> getCarbohydrateContent() {
        return getNutrition("carbohydrateContent");
    }

    public Optional<Integer> getFatContent() {
        return getNutrition("fatContent");
    }

    public Optional<Integer> getProteinContent() {
        return getNutrition("proteinContent");
    }

    // All Directly generated by IntelliJ

    public long getRecipeId() {
        return protoRecipe.getRecipeId();
    }

    public String getName() {
        return protoRecipe.getName();
    }

    public String getSlug() {
        return protoRecipe.getSlug();
    }

    public String getCrawlUrl() {
        return protoRecipe.getCrawlUrl();
    }

    public String getImageUrl() {
        return protoRecipe.getImageUrl();
    }

    public String getDescription() {
        return protoRecipe.getDescription();
    }

    public String getInstructions() {
        return protoRecipe.getInstructions();
    }

    public List<String> getLabelsList() {
        return protoRecipe.getLabelsList();
    }

    public List<String> getIngredientsList() {
        return protoRecipe.getIngredientsList();
    }

    public List<String> getParsedIngredientsList() {
        return protoRecipe.getParsedIngredientsList();
    }

    public List<Integer> getIngredientsBadIndicesList() {
        return protoRecipe.getIngredientsBadIndicesList();
    }
}

